- name: variable from files
  hosts: localhost
  vars_files:
    - course.yaml
  tasks:
  - name: print msg
    ansible.builtin.debug:
      msg:  "{{ COURSE }} is a course by {{ TRAINER }} and it lasts for {{ DURATION }}"