- name: condition using prompt
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: number
      prompt: "Enter a number to check if it is even or odd"
      private: false

  tasks:
    - name: print if number is even
      ansible.builtin.debug:
        msg: "The number {{ number }} is even"
      when: number | int % 2 == 0

    - name: print if number is odd
      ansible.builtin.debug:
        msg: "The number {{ number }} is odd"
      when: number | int % 2 != 0
