- name: condition using prompt
  hosts: localhost
  vars_prompt:
    - name: number
      prompt: "Enter a number to check if it is even or odd"
      private: true
  tasks:
  - name: print if number is even
    ansible.builtin.debug:
      msg: "The number {{ number }} is even"
    when: number % 2 == 0

  - name: print if number is odd
    ansible.builtin.debug:
      msg: "The number {{ number }} is odd"
    when: number % 2 != 0